In [1]:
import pandas as pd
import custom
from IPython.display import display

In [2]:
df = pd.read_csv("data/critic_reviews.csv")
#필요없는 열 삭제
df = df[["quote","scoreSentiment"]]
display(df)

C:\Users\jinsa\AppData\Local\Temp\ipykernel_3264\3036218454.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/critic_reviews.csv")

                                                    quote scoreSentiment
0       Terry Gilliam's third fantasy feature may not ...       POSITIVE
1                                                     NaN       POSITIVE
2       Weir, working from a script by Rafael Yglesias...       POSITIVE
3       Coming out from behind Spike Lee's camera, Ern...       POSITIVE
4                                                     NaN       NEGATIVE
...                                                   ...            ...
967559  SORRY&#47;NOT SORRY is a thought-provoking doc...       POSITIVE
967560  If you want proof that some in Hollywood and t...       POSITIVE
967561  It’s about how men like Louis get away with th...       POSITIVE
967562  Sorry&#47;Not Sorry is an eye opening condemna...       POSITIVE
967563  A painful, anger-inducing reminder of how soci...       POSITIVE

[967564 rows x 2 columns]

In [3]:
#결측치 삭제
df = df.drop(df[df.isnull().sum(axis = 1) > 0].index, axis = 0 )
#POSITIVE, NEGATIVE 숫자로(t)
df = df.replace({"scoreSentiment" : {"POSITIVE" : 1}})
df = df.replace({"scoreSentiment" : {"NEGATIVE" : 0}})
#문장 전처리
for i in range(len(df)) :
    df.iloc[i, 0] = custom.text_preprocess(df.iloc[i, 0])
#단어길이열 추가 (padding 작업용)
word_len = []
for s in df["quote"].values.tolist() :
    word_len.append(len(s.split()))
df["word_len"] = word_len
#출력
display(df)

C:\Users\jinsa\AppData\Local\Temp\ipykernel_3264\514119538.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({"scoreSentiment" : {"NEGATIVE" : 0}})

,quote,scoreSentiment,word_len
0,terry gilliam s third fantasy feature may not ...,1,28
2,weir working from a script by rafael yglesias ...,1,29
3,coming out from behind spike lee s camera erne...,1,32
7,still despite its heavy mood and intricate plo...,1,30
9,it s the sort of film that can only be watched...,0,25
...,...,...,...
967559,sorry N not sorry is a thought provoking docum...,1,39
967560,if you want proof that some in hollywood and t...,1,33
967561,it s about how men like louis get away with th...,1,44
967562,sorry N not sorry is an eye opening condemnati...,1,35
967563,a painful anger inducing reminder of how socie...,1,15

In [4]:
df.to_csv("data/movie_data.csv")

In [5]:
#단어 10개 초과 제거 
df = df.drop(df[df["word_len"] > 10].index, axis = 0)
df.to_csv("data/simple_movie_data.csv")